import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { NextAuthProvider } from "@/lib/authProvider/authProvider"
import { ChakraProviderCustom } from "@/lib/chakraProvider/chakraProvider"
import { ApolloProviderCustom } from "@/lib/apolloProvider/provider"
import { getServerSession } from "next-auth/next"
import { authConfig } from "@/lib/authProvider/auth"
import { Toaster } from "react-hot-toast"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authConfig)
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider session={session}>
          <ApolloProviderCustom>
            <ChakraProviderCustom>
              {children}
              <Toaster />
            </ChakraProviderCustom>
          </ApolloProviderCustom>
        </NextAuthProvider>
      </body>
    </html>
  )
}
